name: Test node-sass

on:
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} node-sass ${{ matrix.node-sass-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
        node-sass-version:
          - v4.14.1
          - v5.0.0
          - v6.0.0

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: node bin/download-node-modules-assets node-sass ${{ matrix.node-sass-version }}