name: Test cypress

on:
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} cypress ${{ matrix.cypress-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
        cypress-version:
          - 7.3.0
          - 6.9.1
          - 5.6.0

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: node bin/download-node-modules-assets cypress ${{ matrix.cypress-version }}