name: Test electron

on:
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} electron ${{ matrix.electron-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
        electron-version:
          - v11.4.7
          - v12.0.8
          - v13.0.0-beta.22

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: node bin/download-node-modules-assets electron ${{ matrix.electron-version }}